defaults:
 - dataset: mnist
 - optimizer: sgd

batch_size: 128
epochs: 40
nz: 100

cuda: false
sample_dir: images
model_dir: checkpoints
resume: false
clean: false
checkpoint: true
checkpoint_incr: false
# data_dir: data
